spring:
  data:
    redis:
      host: 81.71.96.88
      port: 6379
      #      password: "root"
      database: 0
      client-type: jedis
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 2000ms
      connect-timeout: 2000ms
      timeout: 1000ms

#配置Zookeeper连接信息
zookeeper.address: 127.0.0.1:2181