server.port: 8080
#配置自己的MySQL数据库连接信息
spring.dada.datasource.url: jdbc:mysql://localhost:3306/
spring.datasource.username: root
spring.datasource.password: 123456

#配置Redis连接信息
spring.redis.host: localhost
spring.redis.port: 6379

#配置Zookeeper连接信息
zookeeper.address: 127.0.0.1:2181